-- TOTAL COUNT OF CARS PER BRAND

SELECT BRAND, COUNT(BRAND) AS COUNT_
FROM WEBOFFERS
GROUP BY BRAND
ORDER BY BRAND

-- TOTAL COUNT OF CARS PER BRAND AND PERCENTAGE OF EACH CARS 

SELECT 
	BRAND, 
	COUNT(BRAND) AS COUNT_,
	ROUND(
	CONVERT(FLOAT,COUNT(*))/(SELECT COUNT(*) FROM WEBOFFERS) *100, 2 
	)AS PERCENT_
FROM WEBOFFERS
GROUP BY BRAND
ORDER BY BRAND

-- TOTAL NUMBERS OF ADS PER CITY

SELECT 
	CITY,
	COUNT(W.ID) AS COUNT_
FROM CITY AS C
	JOIN WEBOFFERS AS W 
		ON C.ID = W.CITYID
GROUP BY C.CITY
ORDER BY 2 DESC

-- SEARCH FOR THE CONDITION BELOW

SELECT NAMESURNAME,CITY, BRAND, MODEL,PRICE, YEAR_, KM, FROMWHO,  SHIFTTYPE, FUEL  FROM WEBOFFERS AS W
JOIN CITY AS C ON W.CITYID = C.ID
JOIN USER_ AS U ON W.USERID = U.ID
WHERE
CITY = 'İstanbul' AND
FROMWHO = 'Sahibinden' AND
YEAR_ BETWEEN 2014 AND 2018 AND
SHIFTTYPE = 'otomatik vites' AND
FUEL = 'dizel' AND
BRAND = 'Volkswagen' AND
MODEL = 'Passat'
ORDER BY KM, PRICE 

-- 


