--- 1. Find employees who are currently working

SELECT NAME, SURNAME 
FROM PEOPLE
WHERE OUTDATE IS NULL

--- 2. Find male and female employes who are currently employed by their respectice departments

SELECT D.DEPARTMENT, P.GENDER, COUNT(P.GENDER) AS PERSONCOUNT
FROM DEPARTMENTS AS D 
JOIN PEOPLE AS P
	ON D.ID = P.DEPARTMENTID
WHERE OUTDATE IS NULL
GROUP BY D.DEPARTMENT, GENDER
ORDER BY  D.DEPARTMENT;

Alternative way 1

SELECT D.DEPARTMENT,
CASE
	WHEN P.GENDER = 'E' THEN 'ERKEK'
	ELSE 'KADIN' 
END AS GENDER,
COUNT(P.GENDER) AS PERSONCOUNT
FROM DEPARTMENTS AS D 
JOIN PEOPLE AS P
	ON D.ID = P.DEPARTMENTID
WHERE OUTDATE IS NULL
GROUP BY D.DEPARTMENT, GENDER
ORDER BY  D.DEPARTMENT;

Alternative way 2

SELECT *,
(SELECT COUNT(*) FROM PEOPLE WHERE DEPARTMENTID = D.ID AND GENDER= 'E' AND OUTDATE IS NULL) AS MALES,
(SELECT COUNT(*) FROM PEOPLE WHERE DEPARTMENTID = D.ID AND GENDER= 'K' AND OUTDATE IS NULL) AS FEMALES
FROM DEPARTMENTS AS D
ORDER BY D.DEPARTMENT

--- 3. Find the minimum, maximum and avarage salary of position 'PLANLAMA ŞEFİ'

SELECT 
	POSITION, 
	MIN(SALARY) AS MINSALARY, 
	MAX(SALARY) AS MAXSALARY, 
	ROUND(AVG(SALARY),0) AS AVGSALARY
FROM POSITIONS AS P
	JOIN PEOPLE AS PE 
		ON P.ID = PE.POSITIONID
WHERE P.POSITION = 'PLANLAMA ŞEFİ'
GROUP BY POSITION

--- 4. Find the number of employees per position and their avarage salaries

SELECT 
	PO.POSITION,
	COUNT(P.ID) AS PERSONCOUNT,
	ROUND(AVG(P.SALARY),0) AS AVG_SALARY
FROM POSITIONS AS PO
	JOIN PEOPLE AS P 
		ON PO.ID = P.POSITIONID
WHERE OUTDATE IS NOT NULL
GROUP BY PO.POSITION

--- 5. Find the number of male and female employyes hired per year

SELECT YEAR_,
	   COUNT(K) AS FEMALE,
	   COUNT(E) AS MALE
FROM
	(SELECT DATEPART(YEAR,INDATE) AS YEAR_, 
		CASE WHEN GENDER = 'K' THEN 1 END AS K,
		CASE WHEN GENDER = 'E' THEN 1 END AS E
	FROM PEOPLE) AS P
WHERE YEAR_ IS NOT NULL
GROUP BY YEAR_
ORDER BY YEAR_

--- 6. Find the total working time of each employee and showcase the time in months

SELECT 
	CONCAT(NAME, ' ' ,SURNAME) AS PERSON,
	INDATE,
	OUTDATE,
	CASE
		WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
		ELSE DATEDIFF(MONTH,INDATE,GETDATE())
	END AS WORKINGTIME
FROM PEOPLE

--- 7. The company has decided to print a shirt with the initials of each employee.
In this scenario I find number of each employes according to the initiasl

SELECT 
CONCAT(SUBSTRING(NAME,1,1), '.', SUBSTRING(SURNAME,1,1)) AS SHORTNAME,
COUNT(ID) AS PERSONCOUNT
FROM PEOPLE
GROUP BY CONCAT(SUBSTRING(NAME,1,1), '.', SUBSTRING(SURNAME,1,1))
ORDER BY COUNT(*) DESC

--- 8. Find the depratmens with avarage salary more than 5000

SELECT
	DEPARTMENT, ROUND(AVG(SALARY),0) AS AVGSALARY
FROM DEPARTMENTS AS D
	JOIN PEOPLE AS P
		ON D.ID = P.DEPARTMENTID
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 5500
ORDER BY AVGSALARY DESC

--- 9. Find the avarage working experience of each department and showcase in month

SELECT DEPARTMENT, AVG(WORKINGTIME)
FROM
(SELECT D.DEPARTMENT, 
CASE WHEN OUTDATE IS NOT NULL THEN DATEDIFF(MONTH,INDATE,OUTDATE)
ELSE DATEDIFF(MONTH,INDATE,GETDATE())
END AS WORKINGTIME
FROM DEPARTMENTS AS D
JOIN PEOPLE AS P ON D.ID = P.DEPARTMENTID) AS T
GROUP BY DEPARTMENT

--- 10. Query the name, position, manager of each employe and showcase them as separate collumns

SELECT 
	CONCAT(P.NAME, ' ', P.SURNAME) AS PERSON,
	PO.POSITION,
	CONCAT(P2.NAME, ' ', P2.SURNAME) AS MANAGER_NAME,
	PO2.POSITION AS MANAGER_POSITION
FROM PEOPLE AS P
	JOIN POSITIONS AS PO
		ON P.POSITIONID = PO.ID
	JOIN PEOPLE AS P2
		ON P.MANAGERID = P2.ID
	JOIN POSITIONS AS PO2
		ON P2.POSITIONID = PO2.ID

